### ISSUE TITLE
Use In Production?

### ISSUE THREAD

**Issue by tigerzhang** [IronsDu/DBProxy#1]
Do you use DBProxy in production?

你们现在有在生产环境使用 DBProxy 吗？

**Comment by IronsDu** [comment]
1、去年项目中用过，但最终由于决策原因项目没上线。
2、你可以clone下来用redis benchmark跑跑测试，看能否达到你的要求。(我去年跑过，比codis稍高，CPU消耗也更低)
3、如果要用，注意一点，要考虑代理服务器单点瓶颈(主要是带宽)的问题。所以或许需要多个代理服务器+多链接redis client。

**Comment by IronsDu** [comment]
hi，请问你对这个项目有什么想法/意见呢？

**Comment by IronsDu** [comment]
是否认为效率其实其次，因为其他的代理服务器效率也可以说不算慢，那么更多的是各种外置功能的完善度？运维方便等？

**Comment by tigerzhang** [comment]
我们在做一个 Redis 相关的项目，之前在找有没有合适的 Redis Proxy 实现可以使用。
我们现在在基于 HunanTV/redis-cerberus 修改

**Comment by IronsDu** [comment]
哈哈，我自己倒觉得我 src 目录里那几个文件实现的更简洁呢，真心希望你可以在 VS 2013下 试试。
[Backend](https://github.com/IronsDu/DBProxy/blob/master/src/Backend.cpp#L160) 处理与Redis后端的链接。
[Client](https://github.com/IronsDu/DBProxy/blob/master/src/Client.cpp#L209) 处理与客户端的链接。
有两个函数需要注意下：
[BackendSession::forward](https://github.com/IronsDu/DBProxy/blob/master/src/Backend.cpp#L215) 
[ClientSession::processCompletedReply](https://github.com/IronsDu/DBProxy/blob/master/src/Client.cpp#L730)

^_^
